title: 孙兴松 - 个人技术简历
description: "[📄 点击下载 PDF 简历](https://github.com/xingsongs/xingsongs.github.io/blob/main/%E5%AD%99%E5%85%B4%E6%9D%BE_18698600513.pdf)"
# remote_theme: pages-themes/architect@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
