title: 孙兴松 - 个人技术简历
description: 专注前端开发/后端架构 | 16年经验
# remote_theme: pages-themes/architect@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
